name: fsapp_shared
description: "Libreria condivisa contenente i model ed i service comuni tra fsapp e fsapp_polfer"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.4.1  
  intl: ^0.18.1
  flutter_local_notifications: ^17.1.2
  http: ^1.2.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  firebase_app_check: ^0.4.1+2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
      - assets/google_logo.png
  uses-material-design: true